DROP TABLE PRICE_ADMIN.CLM_APPLICATION_TOKEN IF EXISTS;    


CREATE TABLE PRICE_ADMIN.CLM_APPLICATION_TOKEN
(
	CLM_APPLICATION_TOKEN_ID  	NUMERIC NOT NULL,       
	APPLICATION_TOKEN_VALUE	  	VARCHAR2(100) NOT NULL,
	EXPIRATION_DATE				DATE NOT NULL, 
	LAST_UPDATE_TMSTMP      		TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,         
	LAST_UPDATE_USER_ID     		VARCHAR2(100) NOT NULL,  
  
  CONSTRAINT CLM_APPLICATION_TOKEN_PK PRIMARY KEY (CLM_APPLICATION_TOKEN_ID)
);


CREATE SYNONYM PUBLIC.CLM_APPLICATION_TOKEN FOR PRICE_ADMIN.CLM_APPLICATION_TOKEN;