DROP TABLE PRICE_ADMIN.CONTRACT_PRICE_PROF_SHIP_DC IF EXISTS;    
drop sequence CONTRACT_PRC_PROF_SHIP_DC_SEQ IF EXISTS;

CREATE TABLE PRICE_ADMIN.CONTRACT_PRICE_PROF_SHIP_DC
(
  CPP_SHIP_DC_SEQ				NUMERIC NOT NULL,
  CONTRACT_PRICE_PROFILE_SEQ		NUMERIC NOT NULL,
  SHIP_DC_NBR					VARCHAR2(100 BYTE) NOT NULL,
  CPP_ATTRIBUTE_COLUMN_DESC      VARCHAR2(100 BYTE),
  CREATE_USER_ID					VARCHAR2(100 BYTE) NOT NULL,
  CREATE_TMSTMP      			TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  EFFECTIVE_DATE      			DATE NOT NULL,
  EXPIRATION_DATE      			DATE NOT NULL,
  
  CONSTRAINT CONTRACT_PRICE_PROF_SHIP_DC_PK PRIMARY KEY (CPP_SHIP_DC_SEQ),
  CONSTRAINT CONTRACT_PRC_PROF_SHIP_DC_UK1 UNIQUE (CONTRACT_PRICE_PROFILE_SEQ,SHIP_DC_NBR)
);

create sequence CONTRACT_PRC_PROF_SHIP_DC_SEQ as integer start with 1000;


CREATE SYNONYM PUBLIC.CONTRACT_PRICE_PROF_SHIP_DC FOR PRICE_ADMIN.CONTRACT_PRICE_PROF_SHIP_DC;