DROP TABLE PRICE_ADMIN.CPP_FURTHERANCE_STATUS IF EXISTS;    

CREATE TABLE PRICE_ADMIN.CPP_FURTHERANCE_STATUS
(	
	FURTHERANCE_STATUS_CODE NUMERIC NOT NULL,
	CODE_TABLE_REF_ID 		NUMERIC NOT NULL,
	LAST_UPDATE_TMSTMP 		TIMESTAMP(6) WITH TIME ZONE DEFAULT systimestamp NOT NULL, 
	LAST_UPDATE_USER_ID 	VARCHAR2(100 BYTE) NOT NULL, 
  
  CONSTRAINT CPP_FURTHERANCE_STATUS_PK	PRIMARY KEY (FURTHERANCE_STATUS_CODE)  
  
);

CREATE SYNONYM PUBLIC.CPP_FURTHERANCE_STATUS FOR PRICE_ADMIN.CPP_FURTHERANCE_STATUS;