DROP TABLE PRICE_ADMIN.CPP_ITEM_MAPPING IF EXISTS;    
drop sequence CPP_ITEM_MAPPING_SEQ IF EXISTS;

CREATE TABLE PRICE_ADMIN.CPP_ITEM_MAPPING
(	
	CPP_ITEM_MAPPING_SEQ         NUMERIC NOT NULL,                    
	CUSTOMER_ITEM_DESC_PRICE_SEQ NUMERIC NOT NULL,                      
	ITEM_PRICE_LEVEL_CODE        NUMERIC NOT NULL,                       
	ITEM_PRICE_ID                VARCHAR2(12) NOT NULL,                
	EFFECTIVE_DATE               DATE DEFAULT trunc(SYSDATE) NOT NULL,                      
	EXPIRATION_DATE              DATE DEFAULT  to_date('01/01/9999', 'MM/DD/YYYY') NOT NULL,                     
	LAST_UPDATE_USER_ID          VARCHAR2(100) NOT NULL,	               
	LAST_UPDATE_TMSTMP           TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, 
	CREATE_USER_ID               VARCHAR2(100) NOT NULL,         
	CREATE_TMSTMP                TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, 
  
  CONSTRAINT CPP_ITEM_MAPPING_PK	PRIMARY KEY (CPP_ITEM_MAPPING_SEQ),
  CONSTRAINT CPP_ITEM_MAPPING_UK1	UNIQUE  (CPP_ITEM_MAPPING_SEQ, CUSTOMER_ITEM_DESC_PRICE_SEQ, ITEM_PRICE_LEVEL_CODE, ITEM_PRICE_ID, EFFECTIVE_DATE, EXPIRATION_DATE)  
  
);

create sequence CPP_ITEM_MAPPING_SEQ as integer start with 1000 ;
CREATE SYNONYM PUBLIC.CPP_ITEM_MAPPING FOR PRICE_ADMIN.CPP_ITEM_MAPPING;