DROP TABLE PRICE_ADMIN.CPP_FURTHERANCE_TRACKING IF EXISTS;    
drop sequence CPP_FURTHERANCE_TRACKING_SEQ IF EXISTS;

CREATE TABLE PRICE_ADMIN.CPP_FURTHERANCE_TRACKING
(	
	CPP_FURTHERANCE_TRACKING_SEQ	NUMERIC NOT NULL, 
	CPP_FURTHERANCE_SEQ 			NUMERIC NOT NULL, 
	FURTHERANCE_ACTION_CODE 		NUMERIC NOT NULL, 
	ITEM_PRICE_ID 					VARCHAR2(50 BYTE) NOT NULL, 
	ITEM_PRICE_LEVEL_CODE 			NUMERIC NOT NULL, 
	CMG_CUSTOMER_ID 				VARCHAR2(9 BYTE) NOT NULL, 
	CMG_CUSTOMER_TYPE_CODE 			NUMERIC NOT NULL, 
	CHANGE_TABLE_NAME 				VARCHAR2(30 BYTE) NOT NULL, 
	CREATE_USER_ID 					VARCHAR2(100 BYTE) NOT NULL, 
	CREATE_TMSTMP 					TIMESTAMP(6) DEFAULT systimestamp NOT NULL, 
	LAST_UPDATE_USER_ID 			VARCHAR2(100 BYTE) NOT NULL, 
	LAST_UPDATE_TMSTMP 				TIMESTAMP(6) WITH TIME ZONE DEFAULT systimestamp NOT NULL, 
  
  CONSTRAINT CPP_FURTHERANCE_TRACKING_PK PRIMARY KEY (CPP_FURTHERANCE_TRACKING_SEQ),
  CONSTRAINT CPP_FURTHERANCE_TRACKING_UK1 UNIQUE (CPP_FURTHERANCE_SEQ, ITEM_PRICE_ID, ITEM_PRICE_LEVEL_CODE, CMG_CUSTOMER_ID, CMG_CUSTOMER_TYPE_CODE, CREATE_TMSTMP) 
  
);

create sequence CPP_FURTHERANCE_TRACKING_SEQ as integer start with 1000 ;
CREATE SYNONYM PUBLIC.CPP_FURTHERANCE_TRACKING FOR PRICE_ADMIN.CPP_FURTHERANCE_TRACKING;
