DROP TABLE PRICE_ADMIN.CPP_CONCEPT_MAPPING IF EXISTS;    
drop sequence CPP_CONCEPT_MAPPING_SEQ IF EXISTS;

CREATE TABLE PRICE_ADMIN.CPP_CONCEPT_MAPPING
(
  	CPP_CONCEPT_MAPPING_SEQ 	NUMERIC NOT NULL, 
 	CPP_CUSTOMER_SEQ 			NUMERIC NOT NULL,
	GFS_CUSTOMER_ID 			VARCHAR2(9) NOT NULL,
	GFS_CUSTOMER_TYPE_CODE 		NUMERIC NOT NULL,
	EFFECTIVE_DATE 			 DATE DEFAULT trunc(SYSDATE) NOT NULL, 
	EXPIRATION_DATE 		     DATE DEFAULT  to_date('01/01/9999', 'MM/DD/YYYY') NOT NULL, 
	LAST_UPDATE_USER_ID 		VARCHAR2(100) NOT NULL,	
	CREATE_USER_ID 				VARCHAR2(100) NOT NULL,
	CREATE_TMSTMP 				TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
	LAST_UPDATE_TMSTMP 			TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, 	      
  
  CONSTRAINT CPP_CONCEPT_MAPPING_PK	PRIMARY KEY (CPP_CONCEPT_MAPPING_SEQ),
  CONSTRAINT CPP_CONCEPT_MAPPING_UK1 UNIQUE  (CPP_CUSTOMER_SEQ, GFS_CUSTOMER_ID, GFS_CUSTOMER_TYPE_CODE, EXPIRATION_DATE)  
  
);

create sequence CPP_CONCEPT_MAPPING_SEQ as integer start with 1000 ;
CREATE SYNONYM PUBLIC.CPP_CONCEPT_MAPPING FOR PRICE_ADMIN.CPP_CONCEPT_MAPPING;