DROP TABLE PRICE_ADMIN.CPP_LANGUAGE_ATTRIBUTE_MAP IF EXISTS;    
drop sequence CPP_LANGUAGE_ATTRIBUTE_MAP_SEQ IF EXISTS;

CREATE TABLE PRICE_ADMIN.CPP_LANGUAGE_ATTRIBUTE_MAP
(
CPP_LANGUAGE_ATTRIBUTE_MAP_SEQ NUMERIC NOT NULL,         
CPP_LANGUAGE_ATTRIBUTE_SEQ     NUMERIC  NOT NULL,       
CPP_ATTRIBUTE_COLUMN_VALUE     VARCHAR2(100), 
CLM_CONTRACT_TYPE_NAME         VARCHAR2(30),  
CPP_LANGUAGE_STATEMENT_SEQ     NUMERIC NOT NULL,         
LAST_UPDATE_USER_ID            VARCHAR2(100) NOT NULL,  
LAST_UPDATE_TMSTMP             TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, 

  CONSTRAINT CPP_LANGUAGE_ATTRIBUTE_MAP_PK PRIMARY KEY (CPP_LANGUAGE_ATTRIBUTE_MAP_SEQ),
  CONSTRAINT CPP_LANGUAGE_ATTRIBUTE_MAP_UK1 UNIQUE (CPP_LANGUAGE_ATTRIBUTE_SEQ,CPP_ATTRIBUTE_COLUMN_VALUE)
);

create sequence CPP_LANGUAGE_ATTRIBUTE_MAP_SEQ as integer start with 1000;


CREATE SYNONYM PUBLIC.CPP_LANGUAGE_ATTRIBUTE_MAP FOR PRICE_ADMIN.CPP_LANGUAGE_ATTRIBUTE_MAP;