DROP TABLE PRICE_ADMIN.CPP_LANGUAGE_ATTRIBUTE IF EXISTS;    
drop sequence CPP_LANGUAGE_ATTRIBUTE_SEQ IF EXISTS;

CREATE TABLE PRICE_ADMIN.CPP_LANGUAGE_ATTRIBUTE
(
  CPP_LANGUAGE_ATTRIBUTE_SEQ		NUMERIC NOT NULL,
  CPP_ATTRIBUTE_COLUMN_NAME		VARCHAR2(100 BYTE) NOT NULL,
  CPP_ATTRIBUTE_COLUMN_DESC      VARCHAR2(100 BYTE),
  LAST_UPDATE_USER_ID			VARCHAR2(100 BYTE) NOT NULL,
  LAST_UPDATE_TMSTMP      		TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  
  CONSTRAINT CPP_LANGUAGE_ATTRIBUTE_PK PRIMARY KEY (CPP_LANGUAGE_ATTRIBUTE_SEQ),
  CONSTRAINT CPP_ATTRIBUTE_COLUMN_NAME UNIQUE (CPP_ATTRIBUTE_COLUMN_NAME)
);

create sequence CPP_LANGUAGE_ATTRIBUTE_SEQ as integer start with 1000;


CREATE SYNONYM PUBLIC.CPP_LANGUAGE_ATTRIBUTE FOR PRICE_ADMIN.CPP_LANGUAGE_ATTRIBUTE;