DROP TABLE PRICE_ADMIN.CPP_FURTHERANCE IF EXISTS;    
drop sequence CPP_FURTHERANCE_SEQ IF EXISTS;

CREATE TABLE PRICE_ADMIN.CPP_FURTHERANCE
(	
	CPP_FURTHERANCE_SEQ 		NUMERIC NOT NULL, 
	CONTRACT_PRICE_PROFILE_SEQ 	NUMERIC NOT NULL, 
 	PRICE_ACTIVATED_TMSTMP 		TIMESTAMP(6),
 	FURTHERANCE_STATUS_CODE 	NUMERIC NOT NULL,
 	PARENT_CLM_AGREEMENT_ID 	VARCHAR2(100 BYTE), 
 	FURTHERANCE_EFFECTIVE_DATE 	DATE NOT NULL, 
 	CHANGE_REASON_TXT 			VARCHAR2(200 BYTE), 
 	CONTRACT_REFERENCE_TXT 		VARCHAR2(1500 BYTE), 
 	FURTHERANCE_DOCUMENT_GUID 	VARCHAR2(100 BYTE), 
 	CREATE_USER_ID 				VARCHAR2(100 BYTE) NOT NULL, 
 	CREATE_TMSTMP 				TIMESTAMP(6) WITH TIME ZONE DEFAULT systimestamp NOT NULL ,
 	LAST_UPDATE_USER_ID 		VARCHAR2(100 BYTE) NOT NULL, 
 	LAST_UPDATE_TMSTMP 			TIMESTAMP(6) WITH TIME ZONE DEFAULT systimestamp NOT NULL,
  
  CONSTRAINT CPP_FURTHERANCE_PK	PRIMARY KEY (CPP_FURTHERANCE_SEQ),
  CONSTRAINT CPP_FURTHERANCE_UK1 UNIQUE (CONTRACT_PRICE_PROFILE_SEQ, PRICE_ACTIVATED_TMSTMP) 
  
);

create sequence CPP_FURTHERANCE_SEQ as integer start with 1000 ;
CREATE SYNONYM PUBLIC.CPP_FURTHERANCE FOR PRICE_ADMIN.CPP_FURTHERANCE;