DROP TABLE PRICE_ADMIN.CPP_FURTHERANCE_ACTION IF EXISTS;    

CREATE TABLE PRICE_ADMIN.CPP_FURTHERANCE_ACTION
(		
	FURTHERANCE_ACTION_CODE NUMERIC NOT NULL, 
 	CODE_TABLE_REF_ID 		NUMERIC NOT NULL, 
 	LAST_UPDATE_TMSTMP 		TIMESTAMP(6) WITH TIME ZONE DEFAULT systimestamp NOT NULL, 
 	LAST_UPDATE_USER_ID 	VARCHAR2(100 BYTE) NOT NULL, 
  
  CONSTRAINT CPP_FURTHERANCE_ACTION_PK	PRIMARY KEY (FURTHERANCE_ACTION_CODE) 
  
);

CREATE SYNONYM PUBLIC.CPP_FURTHERANCE_ACTION FOR PRICE_ADMIN.CPP_FURTHERANCE_ACTION;