DROP TABLE PRICE_ADMIN.CUSTOMER_ITEM_DESC_PRICE IF EXISTS;    
drop sequence CUSTOMER_ITEM_PRICE_SEQ IF EXISTS;

CREATE TABLE PRICE_ADMIN.CUSTOMER_ITEM_DESC_PRICE
(
CUSTOMER_ITEM_DESC_PRICE_SEQ NUMERIC  NOT NULL,       
CONTRACT_PRICE_PROFILE_SEQ   NUMERIC  NOT NULL,      
GFS_CUSTOMER_ID              VARCHAR2(9) NOT NULL,   
GFS_CUSTOMER_TYPE_CODE       NUMERIC  NOT NULL,      
ITEM_DESC                    VARCHAR2(100) NOT NULL, 
COST_MARKUP_AMT              NUMERIC(128,2),        
MARKUP_AMOUNT_TYPE_CODE      VARCHAR2(3),   
MARKUP_UNIT_TYPE_CODE        NUMERIC,        
CREATE_TMSTMP                TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,          
CREATE_USER_ID               VARCHAR2(100) NOT NULL,
LAST_UPDATE_TMSTMP           TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,         
LAST_UPDATE_USER_ID          VARCHAR2(100), 

  
  CONSTRAINT CUSTOMER_ITEM_DESC_PRICE_SEQ PRIMARY KEY (CUSTOMER_ITEM_DESC_PRICE_SEQ),
  CONSTRAINT CUSTOMER_ITEM_DESC_PRICE_UK1 UNIQUE (CONTRACT_PRICE_PROFILE_SEQ,GFS_CUSTOMER_ID,GFS_CUSTOMER_TYPE_CODE,ITEM_DESC)
  
);

create sequence CUSTOMER_ITEM_DESC_PRICE_SEQ as integer start with 1000;

CREATE SYNONYM PUBLIC.CUSTOMER_ITEM_DESC_PRICE FOR PRICE_ADMIN.CUSTOMER_ITEM_DESC_PRICE;