DROP TABLE PRICE_ADMIN.PRC_PROF_AUDIT_AUTHORITY IF EXISTS;    
drop sequence PRC_PROF_AUDIT_AUTHORITY_SEQ IF EXISTS;

CREATE TABLE PRICE_ADMIN.PRC_PROF_AUDIT_AUTHORITY
(

	PRC_PROF_AUDIT_AUTHORITY_SEQ NUMERIC  	NOT NULL,       
	GFS_CUSTOMER_ID              VARCHAR2(9) NOT NULL,    
	GFS_CUSTOMER_TYPE_CODE       NUMERIC  	NOT NULL,       
	EFFECTIVE_DATE               DATE 		NOT NULL,          
	EXPIRATION_DATE              DATE   		NOT NULL,        
	CREATE_TMSTMP                TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,         
	CREATE_USER_ID               VARCHAR2(100) 	NOT NULL,  
	LAST_UPDATE_TMSTMP           TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,         
	LAST_UPDATE_USER_ID          VARCHAR2(100) 	NOT NULL,
	PRC_PROF_AUDIT_AUTHORITY_IND NUMERIC(1)  NOT NULL,    
	CONTRACT_PRICE_PROFILE_SEQ            NUMERIC,        

    CONSTRAINT PRC_PROF_AUDIT_AUTHORITY_PK PRIMARY KEY (PRC_PROF_AUDIT_AUTHORITY_SEQ)
);

create sequence PRC_PROF_AUDIT_AUTHORITY_SEQ as integer start with 1000 ;
CREATE SYNONYM PUBLIC.PRC_PROF_AUDIT_AUTHORITY FOR PRICE_ADMIN.PRC_PROF_AUDIT_AUTHORITY;