DROP TABLE PRICE_ADMIN.PRC_PROF_LESSCASE_RULE IF EXISTS;    
drop sequence PRC_PROF_LESSCASE_RULE_SEQ IF EXISTS;

CREATE TABLE PRICE_ADMIN.PRC_PROF_LESSCASE_RULE
(

PRC_PROF_LESSCASE_RULE_SEQ     NUMERIC NOT NULL,        
GFS_CUSTOMER_ID                VARCHAR2(9) NOT NULL,   
GFS_CUSTOMER_TYPE_CODE         NUMERIC NOT NULL,        
ITEM_PRICE_LEVEL_CODE          NUMERIC NOT NULL,         
ITEM_PRICE_ID                  VARCHAR2(50),  
EFFECTIVE_DATE                 DATE  NOT NULL,        
EXPIRATION_DATE                DATE NOT NULL,           
CREATE_TMSTMP                  TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,         
CREATE_USER_ID                 VARCHAR2(100) NOT NULL,
LAST_UPDATE_TMSTMP             TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,       
LAST_UPDATE_USER_ID            VARCHAR2(100) NOT NULL,  
LESSCASE_PRICE_RULE_ID         NUMERIC NOT NULL,       
CW_MARKUP_AMT                  NUMERIC(128,2),        
CW_MARKUP_AMOUNT_TYPE_CODE     VARCHAR2(3) NOT NULL,    
NON_CW_MARKUP_AMT              NUMERIC(128,2),        
NON_CW_MARKUP_AMOUNT_TYPE_CODE VARCHAR2(3) NOT NULL,   
MARKUP_APPLIED_BEFORE_DIV_IND  NUMERIC DEFAULT 0 NOT NULL,   
CONTRACT_PRICE_PROFILE_SEQ     NUMERIC, 
	

    CONSTRAINT PRC_PROF_LESSCASE_RULE_PK PRIMARY KEY (PRC_PROF_LESSCASE_RULE_SEQ)
);

create sequence PRC_PROF_LESSCASE_RULE_SEQ as integer start with 1000 ;
CREATE SYNONYM PUBLIC.PRC_PROF_LESSCASE_RULE FOR PRICE_ADMIN.PRC_PROF_LESSCASE_RULE;