DROP TABLE PRICE_ADMIN.PRC_PROF_VERIFICATION_PRIVLG IF EXISTS;    
drop sequence PRC_PROF_VERIF_PRIVLG_SEQ IF EXISTS;

CREATE TABLE PRICE_ADMIN.PRC_PROF_VERIFICATION_PRIVLG
(

	PRC_PROF_VERIF_PRIVLG_SEQ    NUMBER NOT NULL,        
	CONTRACT_PRICE_PROFILE_SEQ   NUMBER NOT NULL,        
	EFFECTIVE_DATE               DATE NOT NULL,          
	EXPIRATION_DATE              DATE NOT NULL,          
	PRC_PROF_VERIF_PRIVILEGE_IND NUMBER(1) NOT NULL,     
	LAST_UPDATE_TMSTMP           TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,         
	LAST_UPDATE_USER_ID          VARCHAR2(100) NOT NULL, 
	CREATE_TMSTMP                TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,        
	CREATE_USER_ID               VARCHAR2(100) NOT NULL,

    CONSTRAINT PRC_PROF_VERIF_PRIVLG_PK PRIMARY KEY (PRC_PROF_VERIF_PRIVLG_SEQ),
    CONSTRAINT PRC_PROF_VERIF_PRIVLG_UK1 UNIQUE (CONTRACT_PRICE_PROFILE_SEQ,EFFECTIVE_DATE)
);

create sequence PRC_PROF_VERIF_PRIVLG_SEQ as integer start with 1000 ;
CREATE SYNONYM PUBLIC.PRC_PROF_VERIFICATION_PRIVLG FOR PRICE_ADMIN.PRC_PROF_VERIFICATION_PRIVLG;